-- MySQL Script generated by MySQL Workbench
-- Wed Dec 25 18:02:38 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema pappa
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `pappa` ;

-- -----------------------------------------------------
-- Schema pappa
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pappa` DEFAULT CHARACTER SET utf8 ;
USE `pappa` ;

-- -----------------------------------------------------
-- Table `pappa`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pappa`.`User` ;

CREATE TABLE IF NOT EXISTS `pappa`.`User` (
  `user_id` VARCHAR(50) NOT NULL,
  `team_name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pappa`.`Answer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pappa`.`Answer` ;

CREATE TABLE IF NOT EXISTS `pappa`.`Answer` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` VARCHAR(50) NOT NULL,
  `question_id` INT NOT NULL,
  `answer` INT NOT NULL,
  INDEX `fk_Answer_User_idx` (`user_id` ASC),
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_Answer_User`
    FOREIGN KEY (`user_id`)
    REFERENCES `pappa`.`User` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pappa`.`Question`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pappa`.`Question` ;

CREATE TABLE IF NOT EXISTS `pappa`.`Question` (
  `question_id` INT NOT NULL AUTO_INCREMENT,
  `meta` VARCHAR(300) NOT NULL,
  `media` VARCHAR(50) NULL,
  `answer` INT NOT NULL,
  `choice1` VARCHAR(150) NOT NULL,
  `choice2` VARCHAR(150) NOT NULL,
  `choice3` VARCHAR(150) NOT NULL,
  `choice4` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`question_id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
